remove OpenBSD path in drmGetDeviceFromDevId
drm devices moved to /dev/dri/ a few releases ago

This path was broken by
57e0b055 ("xf86drm: add drmGetDeviceFromDevId")

../xf86drm.c:4575:21: error: use of undeclared identifier 'sbuf'
    if (stat(node, &sbuf))

but it no longer needed.

Signed-off-by: Jonathan Gray <jsg@jsg.id.au>